
[functions.wompi-firma]
enabled = true
verify_jwt = false
import_map = "./functions/wompi-firma/deno.json"
entrypoint = "./functions/wompi-firma/index.ts"

[functions.guardar-deseo]
enabled = true
verify_jwt = false
import_map = "./functions/guardar-deseo/deno.json"
entrypoint = "./functions/guardar-deseo/index.ts"

[functions.telegram-bot]
enabled = true
verify_jwt = false
import_map = "./functions/telegram-bot/deno.json"
entrypoint = "./functions/telegram-bot/index.ts"

[functions.notify-telegram]
enabled = true
verify_jwt = false
import_map = "./functions/notify-telegram/deno.json"
entrypoint = "./functions/notify-telegram/index.ts"

[functions.send-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-email/deno.json"
entrypoint = "./functions/send-email/index.ts"

[functions.wompi-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/wompi-webhook/deno.json"
entrypoint = "./functions/wompi-webhook/index.ts"

[functions.guardar-identidad]
enabled = true
verify_jwt = false
entrypoint = "./functions/guardar-identidad/index.ts"

[functions.close-cycle]
enabled = true
verify_jwt = false
import_map = "./functions/close-cycle/deno.json"
entrypoint = "./functions/close-cycle/index.ts"

[functions.monitor]
enabled = true
verify_jwt = false
import_map = "./functions/monitor/deno.json"
entrypoint = "./functions/monitor/index.ts"


